config-version: 1.0.0
locale: en_US
item:
    material: BREEZE_ROD
    name: "<green><bold>SellWand</bold></green>"
    lore:
        - "<aqua><bold>Uses Left</bold></aqua> <white>: <uses></white>"
    rarity: EPIC
    enchanted: true