config-version: 1.1.0.0
locale: en_US
item:
    item-type: BREEZE_ROD
    name: "<green><bold>SellWand</bold></green>"
    lore:
        - "<aqua><bold>Uses Left</bold></aqua> <white>: <uses></white>"
    options:
        enchantment-glint: true